package ru.ls.aqa.school.addressbook.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.ls.aqa.school.addressbook.appmanager.ApplicationManager;
import ru.ls.aqa.school.addressbook.appmanager.GroupHelper;
import ru.ls.aqa.school.addressbook.appmanager.NavigationHelper;

public class CreateGroupTest extends TestBase {

    @Test
    public void testcreateGroup() {
        NavigationHelper.gotoGroupPage();
        GroupHelper.fillGroupForm("test11", "test22", "test32");
        GroupHelper.submitGriupCreation();
        GroupHelper.returnTOGroupPage();
        ApplicationManager.logout();
    }

}
