package ru.ls.aqa.school.addressbook.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.ls.aqa.school.addressbook.appmanager.SessionHelper;
import ru.ls.aqa.school.addressbook.model.GroupData;

public class CreateGroupTest extends TestBase {

    private final GroupData groupData = new GroupData("name", "footer", "header");

    @Test
    public void testCreateGroup() {
        app.getNavigationHelper().goToGroupPage();
        app.getGroupHelper().clickCreateGroup();
        app.getGroupHelper().fillGroupForm(groupData);
        app.getGroupHelper().submitGroupCreation();
        app.getNavigationHelper().goToGroupPage();
    }
}
