package ru.ls.aqa.school.addressbook.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.ls.aqa.school.addressbook.model.ContactData;

public class CreateNewContactTest extends TestBase {

    private final ContactData contact = new ContactData("name", "lastname", "home", "mailcontact");

    @Test
    public void createNewContact() {
        app.getNavigationHelper().clickCreateContact();
        app.getContactHelper().fillContactForm(contact);
        app.getContactHelper().submitContactCreation();
        app.getNavigationHelper().goToContactPage();
    }
}
