package ru.ls.aqa.school.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.ls.aqa.school.addressbook.appmanager.NavigationHelper;
import ru.ls.aqa.school.addressbook.appmanager.SessionHelper;

public class CreateGroupTest extends TestBase {

    @Test
    public void testcreateGroup() {
        NavigationHelper.gotoGroupPage();
        app.getGroupHelper().clickCreateGroup();
        app.getGroupHelper().fillGroupForm("test11", "test22", "test32");
        app.getGroupHelper().submitGriupCreation();
        NavigationHelper.gotoGroupPage();
        SessionHelper.logout();
    }

}
