package ru.ls.aqa.school.addressbook.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class TestDeletionGroup extends TestBase {

    @BeforeEach
    public void init() {
        app.getNavigationHelper().goToGroupPage();
    }

    @Test
    public void DeletionGroup() {
        app.getGroupHelper().selectGroup();
        app.getGroupHelper().clickDeleteButton();
        app.getNavigationHelper().goToGroupPage();
    }

}
