package ru.ls.aqa.school.addressbook;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;

import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.*;

import org.openqa.selenium.Dimension;

import java.util.*;

public class CreateGroupTest {
    private Map<String, Object> vars;

    @BeforeEach
    public void setUp() {
        Configuration.browser = "chrome";
        vars = new HashMap<>();
        open("http://localhost/addressbook/");
        WebDriverRunner.getWebDriver().manage().window().setSize(new Dimension(2029, 1188));
        login("admin", "secret");
    }

    private static void login(String username, String password) {
        $(byName("user")).click();
        $(byName("user")).val(username);
        $(byName("pass")).click();
        $(byName("pass")).val(password);
        $("input:nth-child(7)").click();
    }

    @AfterEach
    public void tearDown() {
    }

    @Test
    public void testcreateGroup() {
        gotoGroupPage();
        fillGroupForm("test11", "test22", "test32");
        submitGriupCreation();
        returnTOGroupPage();
        logout();
    }

    private static void logout() {
        $(byLinkText("Logout")).click();
    }

    private static void returnTOGroupPage() {
        $(byLinkText("group page")).click();
    }

    private static void submitGriupCreation() {
        $(byName("submit")).click();
    }

    private static void fillGroupForm(String name, String header, String footer) {
        $(byName("new")).click();
        $(byName("group_name")).click();
        $(byName("group_name")).val(name);
        $(byName("group_header")).click();
        $(byName("group_header")).val(header);
        $(byName("group_footer")).click();
        $(byName("group_footer")).val(footer);
    }

    private static void gotoGroupPage() {
        $(byLinkText("groups")).click();
    }
}
